[package]
name = "websocket-motoko"
version = "0.0.1"
description = "IC WebSocket Motoko Impimentetion"
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
base = "0.11.1"
ic-websocket-cdk = "0.3.4"
account-identifier = "1.0.2"
account = "1.0.1"
