[package]
name = "websocket-motoko"
version = "0.0.1"
description = "IC WebSocket Motoko Impimentetion"
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
base = "0.11.1"
ic-websocket-cdk = "0.4.0"
account-identifier = "1.0.2"
account = "1.0.1"
json = "1.0.0"
xtended-numbers = "0.3.1"
merkle-patricia-trie = "1.0.0"
