[package]
name = "account-identifier"
version = "1.0.2"
description = "ICP ledger standard account identifiers"
repository = "https://github.com/letmejustputthishere/account-identifiers"
keywords = [ "accountid", "account", "identifier", "icp", "ledger" ]
license = "MIT"

[dependencies]
sha2 = "0.0.4"
hash = "1.0.0"